---
# Source: hivemq-edge/templates/secret-admin.yml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: "hivemq-edge"
    app.kubernetes.io/instance: "my-edge"
    app.kubernetes.io/version: "2025.3"
  name: hivemq-edge-admin-my-edge
  namespace: default
type: Opaque
data:
  user: YWRtaW4=
  password: aGl2ZW1x
