---
# Source: hivemq-swarm/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-swarm-hivemq-swarm
  namespace: default
  labels:
    app.kubernetes.io/name: hivemq-swarm
    app.kubernetes.io/instance: my-swarm
    app.kubernetes.io/version: "4.35.0"
