controlCenter:
  credentialsSecret:
    name: "control-center-credentials"
    usernameKey: "username-secret-key"
    passwordKey: "password-secret-key"
services:
  - type: control-center
    exposed: true
    containerPort: 8081
