nodes:
  replicaCount: 1
extensions:
  - name: hivemq-custom-test-extension
    enabled: true
    supportsHotReload: false
    requestHeaderSecretName: "custom-extension-auth-secret"
    extensionUri: "http://nginx-service/hivemq-custom-test-extension-2.0.0.zip"
