nodes:
  replicaCount: 1
services:
  - type: mqtt
    exposed: true
    containerPort: 1883

  - type: mqtt
    exposed: true
    containerPort: 1884
    keystoreSecretName: "mqtts-keystore-1884"
    keystorePassword: "a2V5LWNoYW5nZW1lCg==" # key-changeme
    truststoreSecretName: "mqtts-truststore-1884"
    truststoreSecretKey: "truststore.jks"
    truststorePassword: "dHJ1c3QtY2hhbmdlbWUK" # trust-changeme

  - type: mqtt
    exposed: true
    containerPort: 1885
    keystoreSecretName: "mqtts-keystore-1885"
    keystorePasswordSecretName: "mqtts-keystore-password-1885"
    truststoreSecretName: "mqtts-truststore-1885"
    truststorePasswordSecretName: "mqtts-truststore-password-1885"
    tlsClientAuthenticationMode: "REQUIRED"
