nodes:
  podSecurityContext:
    enabled: true
    runAsNonRoot: true
extensions:
  - name: hivemq-distributed-tracing-extension
    extensionUri: preinstalled
    enabled: true
    supportsHotReload: true
    configMapName: "distributed-tracing-configuration"
