[docker]
# https://hub.docker.com/r/rancher/k3s/tags?page=1&name=v1.33
k3s-minimum = { image = "rancher/k3s", tag = "v1.24.17-k3s1", update = false }
k3s-latest = { image = "rancher/k3s", tag = "v1.33.1-k3s1" }
