[versions]
assertj = "3.27.3"
awaitility = "4.3.0"
bouncycastle = "1.80"
fabric8-kubernetes-client = "7.1.0"
hivemq-mqttClient = "1.3.5"
hivemq-platform = "4.38.0"
jackson = "2.18.3"
javassist = "3.30.2-GA"
junit-jupiter = "5.12.1"
junit-platform = "1.12.1"
logback = "1.5.18"
netty = "4.1.119.Final"
rest-assured = "5.5.1"
selenium = "4.30.0"
shrinkwrap = "1.2.6"
slf4j = "2.0.17"
testcontainers = "1.20.6"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
bouncycastle-pkix = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncycastle" }
bouncycastle-prov = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }
fabric8-kubernetes-client = { module = "io.fabric8:kubernetes-client", version.ref = "fabric8-kubernetes-client" }
hivemq-extensionSdk = { module = "com.hivemq:hivemq-extension-sdk", version.ref = "hivemq-platform" }
hivemq-mqttClient = { module = "com.hivemq:hivemq-mqtt-client", version.ref = "hivemq-mqttClient" }
jackson-dataformat-toml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-toml", version.ref = "jackson" }
javassist = { module = "org.javassist:javassist", version.ref = "javassist" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
netty-codec-http = { module = "io.netty:netty-codec-http", version.ref = "netty" }
rest-assured = { module = "io.rest-assured:rest-assured", version.ref = "rest-assured" }
selenium-java = { module = "org.seleniumhq.selenium:selenium-java", version.ref = "selenium" }
selenium-remote-driver = { module = "org.seleniumhq.selenium:selenium-remote-driver", version.ref = "selenium" }
shrinkwrap-api = { module = "org.jboss.shrinkwrap:shrinkwrap-api", version.ref = "shrinkwrap" }
shrinkwrap-impl = { module = "org.jboss.shrinkwrap:shrinkwrap-impl-base", version.ref = "shrinkwrap" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-hivemq = { module = "org.testcontainers:hivemq", version.ref = "testcontainers" }
testcontainers-junitJupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-k3s = { module = "org.testcontainers:k3s", version.ref = "testcontainers" }
testcontainers-selenium = { module = "org.testcontainers:selenium", version.ref = "testcontainers" }

[plugins]
oci = { id = "io.github.sgtsilvio.gradle.oci", version = "0.22.0" }
