[versions]
assertj = "3.26.3"
awaitility = "4.2.2"
bouncycastle = "1.79"
fabric8-kubernetes-client = "6.13.4"
hivemq-mqttClient = "1.3.4"
hivemq-platform = "4.35.0"
javassist = "3.30.2-GA"
junit-jupiter = "5.11.3"
junit-platform = "1.11.3"
logback = "1.5.12"
netty = "4.1.115.Final"
# https://hub.docker.com/_/nginx/tags?page=&page_size=&ordering=&name=1.27
nginx-container = "1.27.1"
rest-assured = "5.5.0"
selenium = "4.27.0"
shrinkwrap = "1.2.6"
slf4j = "2.0.16"
testcontainers = "1.20.4"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
bouncycastle-pkix = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncycastle" }
bouncycastle-prov = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }
fabric8-kubernetes-client = { module = "io.fabric8:kubernetes-client", version.ref = "fabric8-kubernetes-client" }
hivemq-extensionSdk = { module = "com.hivemq:hivemq-extension-sdk", version.ref = "hivemq-platform" }
hivemq-mqttClient = { module = "com.hivemq:hivemq-mqtt-client", version.ref = "hivemq-mqttClient" }
javassist = { module = "org.javassist:javassist", version.ref = "javassist" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform"}
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
netty-codec-http = { module = "io.netty:netty-codec-http", version.ref = "netty" }
rest-assured = { module = "io.rest-assured:rest-assured", version.ref = "rest-assured" }
selenium-java = { module = "org.seleniumhq.selenium:selenium-java", version.ref = "selenium" }
selenium-remote-driver = { module = "org.seleniumhq.selenium:selenium-remote-driver", version.ref = "selenium" }
shrinkwrap-api = { module = "org.jboss.shrinkwrap:shrinkwrap-api", version.ref = "shrinkwrap" }
shrinkwrap-impl = { module = "org.jboss.shrinkwrap:shrinkwrap-impl-base", version.ref = "shrinkwrap" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-hivemq = { module = "org.testcontainers:hivemq", version.ref = "testcontainers" }
testcontainers-junitJupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-k3s = { module = "org.testcontainers:k3s", version.ref = "testcontainers" }
testcontainers-selenium = { module = "org.testcontainers:selenium", version.ref = "testcontainers" }
