{{- if .Values.customLogbackConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "hivemq-edge.labels" . | nindent 4 }}
  name: {{ include "hivemq-edge.name" (dict "prefix" "hivemq-edge" "name" "logback" "releaseName" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
data:
  logback.xml: |
    {{- .Values.customLogbackConfig | nindent 4 }}
{{- end }}
