#file: noinspection UndefinedAction,UndefinedParamsPresent
name: HiveMQ Legacy Operator Helm Chart Integration Tests
on:
  workflow_call:
env:
  check-prefix: "Test #"
  split-total: 6
jobs:
  generate-split-index-json:
    name: Generate split Legacy Operator integration tests indexes
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.generate.outputs.split-index-json }}
    steps:
      - name: Generate split index list
        id: generate
        uses: donnerbart/split-tests-java-action/generate-split-index-json@2c851c10022503c980f3f5c323e2af370bc1fd86 # v1
        with:
          split-total: ${{ env.split-total }}

  compile-integration-test:
    name: Compile Legacy Operator integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HiveMQ Helm Charts
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          path: helm-charts
          fetch-depth: 0

      - name: Checkout HiveMQ Legacy Operator
        uses: ./helm-charts/.github/actions/checkout-repo
        with:
          repository: hivemq/hivemq-operator
          repository-default-branch: master
          path: hivemq-operator
          token: ${{ secrets.JENKINS_GITHUB_TOKEN }}

      - name: Set up JDK 21
        id: setup-java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5
        with:
          cache: gradle
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5

      - name: Warmup Gradle cache
        if: steps.setup-java.outputs.cache-hit == 'false'
        working-directory: helm-charts
        run: ./gradlew :tests-hivemq-operator:integrationTestPrepare

  run-integration-tests:
    name: "Test #${{ matrix.split-index }} (${{ matrix.k8s-version-type }})"
    runs-on: ubuntu-latest
    needs:
      - generate-split-index-json
      - compile-integration-test
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        split-index: ${{ fromjson(needs.generate-split-index-json.outputs.json) }}
        k8s-version-type: [
          MINIMUM,
          LATEST
        ]
    steps:
      - name: Checkout HiveMQ Helm Charts
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          path: helm-charts
          fetch-depth: 0

      - name: Checkout HiveMQ Legacy Operator
        uses: ./helm-charts/.github/actions/checkout-repo
        with:
          repository: hivemq/hivemq-operator
          repository-default-branch: master
          path: hivemq-operator
          token: ${{ secrets.JENKINS_GITHUB_TOKEN }}

      - name: Checkout JUnit reports
        uses: donnerbart/split-tests-java-action/checkout-junit-reports@2c851c10022503c980f3f5c323e2af370bc1fd86 # v1
        with:
          split-index: ${{ matrix.split-index }}
          git-branch: junit-reports/legacy/${{ github.base_ref }}
          path: junit-reports
          artifact-name: junit-xml-reports-legacy-sha
          upload-artifact: ${{ matrix.k8s-version-type == 'LATEST' }}

      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

      - name: Login to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5
        with:
          cache: gradle
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5

      - name: Compile integration tests
        working-directory: helm-charts
        run: ./gradlew :tests-hivemq-operator:integrationTestPrepare

      - name: Split tests
        id: split-tests
        uses: donnerbart/split-tests-java-action@2c851c10022503c980f3f5c323e2af370bc1fd86 # v1
        with:
          split-index: ${{ matrix.split-index }}
          split-total: ${{ env.split-total }}
          glob: '**/helm-charts/tests-hivemq-operator/**/*IT.java'
          junit-glob: '**/junit-reports/*.xml'
          format: 'gradle'
          new-test-time: 'average'
          calculate-optimal-total-split: true
          debug: true

      - name: Run integration tests
        working-directory: helm-charts
        env:
          K8S_VERSION_TYPE: ${{ matrix.k8s-version-type }}
        run: ./gradlew :tests-hivemq-operator:integrationTest ${{ steps.split-tests.outputs.test-suite }}

      - name: Upload test results
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: "HiveMQ Legacy Operator - Integration test results #${{ matrix.split-index }} (${{ matrix.k8s-version-type }})"
          path: |
            helm-charts/tests-hivemq-operator/build/reports/tests/integrationTest/
            helm-charts/tests-hivemq-operator/build/test-results/integrationTest/*.xml
          retention-days: 5

      - name: Upload JUnit report artifact
        if: matrix.k8s-version-type == 'LATEST'
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: junit-xml-reports-legacy-${{ matrix.split-index }}
          path: |
            helm-charts/tests-hivemq-operator/build/test-results/integrationTest/*.xml

      - name: Publish test report
        if: ${{ !cancelled() }}
        uses: dorny/test-reporter@7b7927aa7da8b82e81e755810cb51f39941a2cc7 # v2
        with:
          name: Legacy Integration tests report
          path: '**/build/test-results/integrationTest/TEST-*.xml'
          reporter: java-junit
          fail-on-error: false
          working-directory: helm-charts

      - name: Install xmllint
        if: failure()
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Set annotations for failed tests
        if: failure()
        run: |
          find helm-charts/tests-hivemq-operator/build/test-results/integrationTest -type f -name "*.xml" | while read -r FILE; do
            COUNT=$(xmllint --xpath 'count(//testcase[failure or error])' "$FILE")
            for INDEX in $(seq 1 "$COUNT"); do
              TEST_CLASS=$(xmllint --xpath "string((//testcase[failure or error])[$INDEX]/@classname)" "$FILE" 2>/dev/null)
              TEST_METHOD=$(xmllint --xpath "string((//testcase[failure or error])[$INDEX]/@name)" "$FILE" 2>/dev/null)
              MESSAGE=$(xmllint --xpath "string((//testcase[failure or error])[$INDEX]/failure/@message | (//testcase[failure or error])[$INDEX]/error/@message)" "$FILE" 2>/dev/null)
              [ -z "$MESSAGE" ] && MESSAGE="Test failed"
              echo "::error title=Test #${{ matrix.split-index }}::$TEST_CLASS.$TEST_METHOD%0A$MESSAGE"
            done
          done

  merge-junit-reports:
    name: Merge Legacy Operator JUnit reports
    runs-on: ubuntu-latest
    needs:
      - run-integration-tests
    permissions:
      contents: write
    steps:
      - name: Merge JUnit reports
        uses: donnerbart/split-tests-java-action/merge-junit-reports@2c851c10022503c980f3f5c323e2af370bc1fd86 # v1
        with:
          git-branch: junit-reports/legacy/${{ github.base_ref }}
          artifact-name: junit-xml-reports-legacy-${{ github.base_ref }}
          split-artifact-pattern: junit-xml-reports-legacy-*
