name: HiveMQ Platform Operator Helm Chart and HiveMQ Platform Helm Chart Verify Tests
on:
  workflow_call:
jobs:
  run-verify-tests:
    name: Verify tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HiveMQ Helm Charts
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4

      - name: Set up Kubeconform
        run: |
          helm plugin install https://github.com/jtyr/kubeconform-helm --verify=false

      - name: Lint
        if: always()
        run: |
          helm lint charts/hivemq-platform
          helm lint charts/hivemq-platform-operator

      - name: Unit Test
        if: always()
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git --verify=false
          helm unittest "./charts/hivemq-platform-operator" -f ./tests/**/*_test.yaml
          helm unittest "./charts/hivemq-platform" -f ./tests/**/*_test.yaml

      - name: Check manifests are up-to-date
        if: always()
        run: |
          manifests/hivemq-platform/manifests.sh
          manifests/hivemq-platform-operator/manifests.sh
          git add manifests/ -v
          git diff HEAD --exit-code

      - name: Parse HiveMQ Platform Operator CRD from OpenAPI to JSON schema
        if: always()
        run: |
          export FILENAME_FORMAT='{kind}.{group}-{version}'
          .github/openapi2jsonschema.py charts/hivemq-platform-operator/crds/hivemq-platforms.hivemq.com-v1.yml

      - name: Validate rendered manifests
        if: always()
        run: |
          helm kubeconform --config .github/configs/kubeconform.yml charts/hivemq-platform -r hivemq-platform-release -n hivemq-platform-namespace --schema-location hivemqplatform.hivemq-v1.json
          helm kubeconform --config .github/configs/kubeconform.yml charts/hivemq-platform-operator -r hivemq-platform-operator-release -n hivemq-platform-operator-namespace

